version: '2.2'

services:
#  monitor:
#    image: docker.pkg.github.com/bandar-monitors/monitors/monitor:latest
#    environment:
#      MONITORS_SLUG: amazon
#      MONITORS_APPNAME: amazon
#      ConnectionStrings:PostgreSQL: "Server=monitorsdb;Port=5432;Database=monitors;Username=monitors;Password=monitors;"
#      ConnectionStrings:RabbitMq: "amqp://monitors:monitors@rmq:5672/"
#      Otlp:PublisherUrl: "http://ec2-18-116-130-20.us-east-2.compute.amazonaws.com:4317"
  monitorsdb:
    image: postgres:13
    volumes:
      - ./monitors/data/psql/data:/var/lib/postgresql/data
      - ./monitors/data/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: monitors
      POSTGRES_PASSWORD: monitors
      POSTGRES_DB: monitors
    ports:
      - 15432:5432

  paneldb:
    image: postgres:13
    volumes:
      - ./panel/data/psql/data:/var/lib/postgresql/data
      - ./panel/data/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: monitors-panel
      POSTGRES_PASSWORD: monitors-panel
      POSTGRES_DB: monitors-panel
    ports:
      - 25432:5432

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rmq
    environment:
      RABBITMQ_DEFAULT_USER: monitors
      RABBITMQ_DEFAULT_PASS: monitors
    volumes:
      #      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      #      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./monitors/data/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rmq
      - ./monitors/data/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672