FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /monitors-panel
COPY ./src/dotnet ./
WORKDIR manager/MonitorsPanel.Web.ManagerApi
RUN dotnet restore && dotnet publish -c Debug -o ../../dist

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app


##############################
### Remote debug stuff
##############################

RUN apt-get update
RUN apt-get install -y openssh-server openrc curl

RUN mkdir -p /var/run/sshd && chmod 0755 /var/run/sshd
RUN /usr/bin/ssh-keygen -A
RUN /usr/sbin/sshd
RUN ssh-keygen -t rsa -P '' -f /root/.ssh/id_rsa
RUN cat ~/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
RUN chmod 0600 /root/.ssh/authorized_keys
RUN chmod 644 /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa
RUN chmod 700 /root/.ssh

RUN	sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config
RUN echo "root:root" | chpasswd
RUN /etc/init.d/ssh restart
CMD ["/usr/sbin/ssh","-D"]
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -r linux-x64 -v latest -l ~/vsdbg

############################


COPY --from=build-env /monitors-panel/dist .
ENTRYPOINT ["dotnet", "MonitorsPanel.Web.ManagerApi.dll"]
EXPOSE 443
EXPOSE 80
EXPOSE 22
