/**
 * Monitors Panel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentStatsEntry } from './component-stats-entry.model';
import { ApiError } from './api-error.model';


export interface StringComponentStatsEntryArrayDictionaryApiContract { 
    error?: ApiError;
    readonly payload?: { [key: string]: Array<ComponentStatsEntry>; } | null;
}

